# The CMNN Photoz Estimator
A Python3 implementation of the Color-Matched Nearest-Neighbors (CMNN) photometric redshift estimator.<br>
Melissa L. Graham and Andrew J. Connolly, 2020. <br>

**Package Dependencies:** os, datetime, matplotlib, numpy, and scipy.
<br>Verified to run with `Python 3.5.5`, `numpy 1.13.3`, and `scipy 1.1.0`. 

#### Table of Contents
Section 1. An Overview of the CMNN Estimator
<br> Section 2. Capabilities and Boundaries
<br> Section 3. Troubleshooting
<br> Section 4. Examples
<br> Section 5. Module and Function Summaries

#### Links to Associated Resources
["Photometric Redshifts with the LSST: Evaluating Survey Observing Strategies", Graham et al. (2018)](https://ui.adsabs.harvard.edu/abs/2018AJ....155....1G/abstract)
<br>["Photometric Redshifts with the LSST. II. The Impact of Near-infrared and Near-ultraviolet Photometry", Graham et al. (2020)](https://ui.adsabs.harvard.edu/abs/2020AJ....159..258G/abstract)
<br>"Photometric Redshifts with the LSST. III. Tools for Evaluating Survey Strategies", Graham et al. (2021, in prep)
<br>A copy of the input mock galaxy catalog ("LSST\_galaxy\_catalog\_i25p3.dat") can be downloaded from [here](https://drive.google.com/file/d/1OJ0vRtzwJptyF-f4_34j4hvv4_E77mUE/view?usp=sharing).

## Section 1. An Overview of the CMNN Estimator
The color-matched nearest-neighbors (CMNN) photometric redshift (photo-_z_) estimator provides photometric redshifts with an accuracy that is directly dependent on (and only on) the quality of the simulated observed photometry which, as described below, depends directly and only on the $5{\sigma}$ limiting magnitudes (i.e., the LSST survey depths).
This makes it an ideal tool for assessing the impact on photo-_z_ results from different proposed LSST observing strategies that build image depth over time in different ways, or result in different coadded depths.

#### Section 1.1. Simulated Test and Training Sets
The CMNN Estimator uses a _training set_ with known (i.e., spectroscopic) redshifts to estimate photometric redshifts for a _test set_ of galaxies.
In order to simulate a test and training set of galaxies with photometry that represents any desired LSST observing strategy, we start with the same mock galaxy catalog as used in the Graham et al. series of papers listed above.
As in those works, the observed apparent magnitudes and errors for filters _ugrizy_ for all galaxies are simulated based on the true catalog apparent magnitudes and the predicted $5{\sigma}$ limiting magnitude depths for any given LSST observing strategy.
The photometric error, $\sigma_{\rm rand}$, is given in Section 3.2.1 of [Ivezić et al. (2019)](https://ui.adsabs.harvard.edu/abs/2019ApJ...873..111I/abstract): $\sigma^2_{\rm rand} = (0.04-\gamma)x + \gamma x^2$, where $x=10^{0.4(m-m_5)}$, $m_5$ is the $5\sigma$ limiting magnitude, $m$ is the magnitude of the galaxy, and for the LSST optical filters the values for $\gamma$, which sets the impact of, e.g., sky brightness, are $0.037$, $0.038$, $0.039$, $0.039$, $0.04$, and $0.04$ for filters _ugrizy_, respectively.
A random value drawn from a normal distribution with a standard deviation equal to the photometric error for each galaxy is added to the true catalog magnitude to generate observed apparent magnitudes.
For example, the photometric error of a galaxy with a true catalog magnitude of $i=24.5$ mag would be $\sigma_{\rm rand} = 0.026$; a random normal draw of $0.054$ would lead to an observed apparent magnitude of $i=24.55$ mag.
Observed apparent colors are calculated from the observed apparent magnitudes, and the error in the color is the photometric errors added in quadrature.

#### Section 1.2. Estimating Photometric Redshifts
For each galaxy in the test set, the estimator identifies a color-matched subset of training galaxies by calculating the Mahalanobis distance in color-space between the test galaxy and all training galaxies:<br>
$D_M = \sum_{\rm 1}^{N_{\rm colors}} \frac{( c_{\rm train} - c_{\rm test} )^2}{ (\delta c_{\rm test})^2}$<br>
where $c$ is the color of the test- or training-set galaxy, $\delta c_{\rm test}$ is the uncertainty in the test galaxy's color, and $N_{\rm color}$ is the number of colors measured for both the test- and training-set galaxy. 
A threshold value is then applied to all training-set galaxies to identify those which are well-matched in color, as defined by the percent point function (PPF): e.g., if the number of degrees of freedom $N_{\rm color}=5$, PPF$=68\%$ of all training galaxies consistent with the test galaxy will have $D_M < 5.86$.
A training galaxy is then selected by one of three modes from this subset of color-matched nearest-neighbors, and its redshift is used as the test-set galaxy's photometric redshift.
The three modes of selection are to choose randomly, to choose the galaxy with the lowest $D_M$, or to weight the random selection by the inverse of the $D_M$.
The standard deviation in redshifts of this subset of training galaxies is used as the uncertainty in the photo-_z_ estimate.

#### Section 1.3. Analysis with Statistical Measures
This implementation of the CMNN Estimator will make two types of plots to evaluate the quality of the test set's photometric redshifts: (1) true redshift vs. photometric redshift, and (2) statistical measures in bins of photometric redshift: the standard deviation, bias, and fraction of outliers in the photo-_z_ accuracy, $\Delta z = (|z_{\rm true} - z_{\rm phot}|)/(1+z_{\rm phot})$.

## Section 2. Capabilitites and Boundaries

**A single command to generate mock catalogs, simulate photo-_z_, and generate analyses:** This repository allows the user to specify $5{\sigma}$ limiting magnitude depths for the 6 Rubin Observatory filters _ugrizy_, sizes and magnitude cut-offs of the test and training sets, and other parameters for the CMNN Estimator, all in a single command-line call to `cmnn_run.py`.
The codes will then generate test and training sets with appropriate simulated apparent magnitudes and errors, estimate photometric redshifts for test set galaxies, and perform a statistical analysis which generates diagnostic plots, all based on this single input.
A single command-line call to `cmnn_run.py` generates a single simulation, called a `run`, and the user specifies the `runid` which names the output directory where the results are saved.

**The mock catalog** ("LSST\_galaxy\_catalog\_i25p3.dat") contains _ugrizy_ photometry only (no UV or NIR), is limited to galaxies with true apparent magnitudes $i\leq25.3$ mag, and the test and training sets may not include galaxies with simulated observed magnitudes $i>25$ mag.
This matches the $i\leq25$ mag "gold sample" defined by the Science Requirement Document (ls.st/lpm-17), and matches many of the photo-_z_ simulations in the Graham et al. suite of papers listed above.
For access to a deeper catalog, contact the author; some hard-coded changes to `cmnn\_catalog.py` will be required.

**User-specified parameters for the statistical analyses.** The default parameter settings for the analysis plots (true _vs._ photometry redshift, statistical measures in bins of photo-_z_) can be changed by the user with direct calls to the functions in `cmnn_analysis.py`. 
For example, the user can choose from a variety of alternative statistical measures, change the parameter that controls how (and whether) catastrophic outliers are omitted from the statistics, choose to plot the true or photometric redshift on the abscissa, and change the binning parameters.
Users may also choose to plot the results of _multiple_ runs (simulations) on a single plot of the statistical measures as a function of binned photo-_z_, as described below in the notes for the `make_stats_plots` function of `cmnn_analysis.py`. 

## Section 3. Troubleshooting
Here are some solutions to reported issues.

#### Indexing the thresholds array.
In the program cmnn\_photo.zpy, there is this code block: 
<br> `thresholds[i] = thresh_table[ DegreesOfFreedom[i] ]`
<br> which might throw errors for some people, which can be fixed by changing it to:
<br> `thresholds[i] = thresh_table[ int(DegreesOfFreedom[i]) ]`.
<br>

## Section 4. Examples

### Ex. A. Photo-z results for a given year of the baseline observing strategy.

#### A.1 Obtain the 5$\sigma$ limiting magnitudes for years 1, 3, 5, and 10.
Use the `cmnn_tools.py` module to get the limiting magnitues for a baseline survey.
```
path/CMNN_Photoz_Estimator: python
>>> import cmnn_tools
>>> for yr in [1,3,6,10]"
...     print( cmnn_tools.convert_year_to_depths_baseline( yr )
...
[ 24.83523503  26.12886248  26.28102228  25.58102228  24.80514998  23.60514998]
[ 25.4316366   26.72526405  26.87742385  26.17742385  25.40155155  24.20155155]
[ 25.8079241   27.10155155  27.25371134  26.55371134  25.77783904  24.57783904]
[ 26.08523503  27.37886248  27.53102228  26.83102228  26.05514998  24.85514998]
```

#### A.2 Run the CMNN Estimator for each of these desired years.
Pass the 5$\sigma$ limiting magnitudes to the test set input parameters.
The magnitude cuts are set also to the 5$\sigma$ detection limit, with the exception of i-band which should always be set to 25 mag (or brighter).
The training set limits will be kept to the default (the 10-year baseline).
```
python cmnn_run.py --verbose True --runid year1 --test_m5 24.84 26.13 26.28 25.58 24.81 23.61 --test_mcut 24.84 26.13 26.28 25.00 24.81 23.61
python cmnn_run.py --verbose True --runid year3 --test_m5 25.43 26.73 26.88 26.18 25.40 24.20 --test_mcut 25.43 26.73 26.88 25.00 25.40 24.20
python cmnn_run.py --verbose True --runid year6 --test_m5 25.81 27.10 27.25 26.55 25.78 24.58 --test_mcut 25.81 27.10 27.25 25.00 25.78 24.58
python cmnn_run.py --verbose True --runid year10 --test_m5 26.09 27.38 27.53 26.83 26.06 24.86 --test_mcut 26.09 27.38 27.53 25.00 26.06 24.86
```

#### A.3 View the results.
The default plots are in the individual output directories; e.g.,
```
path/CMNN_Photoz_Estimator: open output/run_year1/*.png
```

Make plots comparing the statististical measures for all years and view them.
```
path/CMNN_Photoz_Estimator: python
>>> import cmnn_analysis
>>> cmnn_analysis.make_stats_plots( multi_run_ids=['year1','year3','year6','year10'], multi_run_labels=['Year 1','Year 3','Year 6','Year 10'] )
path/CMNN_Photoz_Estimator: open output/stats_plots/*_year1_year3_year6_year10.png
```
For example, the combined plot for robust standard deviation should look similar to this.
Note that especially the high-_z_ bin values can fluctuate when a low number of test-set galaxies are used, and that the default for N\_test is only 40000 (Table 1).
<img src="example.png" alt="example" style="width: 400px;"/>
<br>

### Ex. B. Use non-overlapping bins in true-redshift to plot the fraction of outliers, standard deviation, and bias.
This ee three deviations from the defaults are: (1) user specifies to use non-overlapping bins (`NOLB`); (2) user specifies to bin in true redshift (`bin_in_truez=True`); and (3) user specifies the statistical measures to be plotted (`user_stats=['fout','stdd','bias']`).
```
path/CMNN_Photoz_Estimator: python
>>> import cmnn_analysis
>>> NOLB_zbins = [ [0.3,0.6],[0.6,0.9],[0.9,1.2],[1.2,1.5],[1.5,1.8],[1.8,2.1],[2.1,2.4],[2.4,2.7],[2.7,3.0] ]
>>> cmnn_analysis.make_stats_file( True, 'year1', 1.5, input_zbins=NOLB_zbins, statsfile_suffix='NOLB', bin_in_truez=True )
>>> cmnn_analysis.make_stats_file( True, 'year3', 1.5, input_zbins=NOLB_zbins, statsfile_suffix='NOLB', bin_in_truez=True )
>>> cmnn_analysis.make_stats_file( True, 'year6', 1.5, input_zbins=NOLB_zbins, statsfile_suffix='NOLB', bin_in_truez=True )
>>> cmnn_analysis.make_stats_file( True, 'year10', 1.5, input_zbins=NOLB_zbins, statsfile_suffix='NOLB', bin_in_truez=True )
>>> cmnn_analysis.make_stats_plots( statsfile_suffix='NOLB', bin_in_truez=True, user_stats=['fout','stdd','bias'], multi_run_ids=['year1','year3','year6','year10'], multi_run_labels=['Year 1','Year 3','Year 6','Year 10'])
```

### Ex. C. Maximizing the size of the test and training sets.
TBD.

## Section 5. Module and Function Summaries

There are five modules in the CMNN Estimator: `cmnn_run`, `cmnn_catalog`, `cmnn_photoz`, `cmnn_analysis`, and `cmnn_tools`.
Of these, only `cmnn_run` can parse user input from the terminal command line.
Each module contains at least two functions, all of which are described below.

### Section 5.1.1. `cmnn_run.main`
Called from the command line.

**What it does:** Parses the command line input. Checks that input values are good. Creates an output directory. Writes a file containing the input values to the output directory. Passes input to the function cmnn_run.run.

**Important notes:** This is the only code which can be called from the command line, and the only code which validates that the user-provided arguments are acceptable values.

**Outputs:** This module records the user input values for all parameters listed in Table 1 to the file output/run\__runid_/inputs.txt.

#### Table 1: All User-Specified Inputs to `cmnn_run.main`
| Inputs$^{(a)}$ | Type | Default | Description |
| :-- | :-- | :-- | :-- |
| verbose | bool | True | if True, prints more intermediate information to the screen |
| runid | str | '1' | unique run identifier for labeling the output files |
| clobber | bool | False | if True, overwrites any existing output for this runid |
| test\_m5 | float[6] | [26.1, 27.4, 27.5, 26.8, 26.1, 24.9]$^{(b)}$ | the 5-sigma magnitude limits (depths) to apply to the test-set galaxies |
| train\_m5 | float[6] | [26.1, 27.4, 27.5, 26.8, 26.1, 24.9]$^{(b)}$ | the 5-sigma magnitude limits (depths) to apply to the training-set galaxies |
| test\_mcut | float[6] | [26.1, 27.4, 27.5, 25.0, 26.1, 24.9]$^{(b)}$ | a magnitude cut-off to apply to the test-set galaxies |
| train\_mcut | float[6] | [26.1, 27.4, 27.5, 25.0, 26.1, 24.9]$^{(b)}$ | a magnitude cut-off to apply to the training-set galaxies |
| force\_idet | bool | True | force detection in _i_-band for all test and train galaxies |
| force\_gridet | bool | True | force detection in _g_, _r_, and _i_-bands for all test and train galaxies |
| test\_N | int | 40000 | number of test-set galaxies | 
| train\_N | int | 200000 | number of training-set galaxies | 
| cmnn\_minNc | int | 3 | minimum number of colors required for inclusion in catalog |
| cmnn\_minNN | int | 10 | forced minimum number of training-set galaxies in the CMNN subset |
| cmnn\_ppf | float | 0.68 | the percent point function that defines the Mahalanobis distance threshold of the CMNN |
| cmnn\_rsel | int | 2 | mode of random selection of a training-set galaxy from the CMNN subset (0 = random; 1 = nearest neighbor; 2 = random weighted by inverse of Mahalanobis distance) |
| cmnn\_ppmag | bool | False | apply a "pseudo-prior" to the training set based on the test-set's i-band magnitude (can only be True if force\_idet=True) |
| cmnn\_ppclr | bool | True | apply a "pseudo-prior" to the training set based on the test-set's g-r and r-i color (can only be True if force\_gridet=True) |
| stats\_COR | float | 1.5 | catastrophic outlier rejection; reject galaxies with $(z_{true}-z_{phot})/(1+z_{phot}) >$ `stats_COR` from the statistical measures of standard deviation and bias |

$^{(a)}$None of these inputs are mandatory because all have default values.

$^{(b)}$The default limiting magnitudes are the 10-year 5$\sigma$ limiting magnitude depths for a baseline observing strategy which accumulates 56, 80, 184, 184, 160, 160 visits in filters _ugrizy_ (both m5 and mcut, except for i-band where mcut=25).

#### Table 2: Failure Modes for `cmnn_run.main`
| Exit Conditions for Invalid User Input (a corresponding error message will be printed to screen) |
| :-- |
| directory "output/run\__runid_/" exists and clobber=False |
| any of the magnitude arrays do not contain 6 floats |
| any of the 5$\sigma$ limits are less than [23.9, 25.0, 24.7, 24.0, 23.3, 22.1] (single-visit depths) |
| any of the 5$\sigma$ limits are greater than [29.0, 29.0, 29.0, 29.0, 29.0, 29.0] (arbitrary maximums) |
| any of the magnitude cuts are less than [17.0, 17.0, 17.0, 17.0, 17.0, 17.0] (nearing saturation) |
| any of the magnitude cuts are greater than [29.0, 29.0, 29.0, 25.0, 29.0, 29.0] (arbitrary, and $i<25$ mag) |
| cmnn\_ppmag is True and force\_idet is False (must require i-band detections to use magnitude psuedo-prior) |
| test\_N is $\leq0$ or $>100000$ |
| train\_N is $\leq0$ or $>1000000$ |
| stats\_COR is $\leq0$ |

###  Section 5.1.2. `cmnn_run.run`
Called by `cmnn_run.main`.

**What it does:** Passes user-specified input to the following modules, in order:
<br>`cmnn_catalog.make_test_and_train`
<br>`cmnn_catalog.make_plots`
<br>`cmnn_photoz.make_zphot`
<br>`cmnn_analysis.make_stats_file`
<br>`cmnn_analysis.make_stats_plots`
<br>`cmnn_analysis.make_tzpz_plot`
<br>`cmnn_analysis.make_hist_plots`

**Outputs**: This module appends the date and time of each stage to output/run\__runid_/timestamps.dat.

###  Section 5.2.1. `cmnn_catalog.make_test_and_train`
Called by `cmnn_run.run`.

**What it does::** Simulates observed apparent magnitudes for test and training sets based on the user-specified 5$\sigma$ limiting magnitudes (test\_m5 and train\_m5), and applies the user-specified cuts (test\_mcut, train\_mcut). Chooses randomly from the full mock catalog to create user-specified number of test and training set galaxies.

**Exit Condition:** If the user input sizes for the test and training sets are larger than what the catalog can support, given the user-supplied magnitude depths and cuts, an error message will be returned and the code will exit without writing. Unfortunately the compatibility of the magnitude depths and cuts with the desired sizes of the test and training set cannot be tested in cmnn\_run.py.

**Outputs:** Writes data files of photometry to output/run\__runid_/test.cat and train.cat.

###  Section 5.2.2. `cmnn_catalog.make_plots`
Called by `cmnn_run.run`.

**What it does:** Generates histograms of the redshifts and apparent magnitudes for the test and training sets, and plots the apparent magnitude error vs. the apparent magnitude for all filters, for the test and training sets.

**Outputs:** Saves plots to the output/run\__runid_/plot\_cats/ directory (hist\_ztrue.png, hist\_mag.png, hist\_mage.png, test\_mag\_vs\_mage.png, and train\_mag\_vs\_mage.png).

###  Section 5.3.1. `cmnn_photoz.make_zphot`
Called by `cmnn_run.run`.

**What it does:** Esimates photometric redshifts using the test and training sets of a given run.

**Outputs:** Writes test-set photo-z file to output/run\__runid_/zphot.cat.

###  Section 5.3.2. `cmnn_photoz.return_photoz`
Called by `cmnn_zphot.make_zphot`.

**What it does:** For a given test-set galaxy and a given training-set of galaxies, estimates the photo-_z_ of the test-set galaxy. 

**Returns:** A three-element array containing the estimated photo-_z_, the photo-_z_ error, and the number of color-matched nearest neighbours identified from the training set.

###  Section 5.4.1. `cmnn_analysis.make_stats_file`
Called by `cmnn_run.run`.

**What it does:** Calculates the photo-z statistics in bins of photo-_z_.
The default is overlapping bins: [0.00,0.30],[0.15,0.45],[0.30,0.60], ... [2.70,3.00].
The photo-_z_ bins cannot be set by the user from `cmnn_run.run`, but when calling the module directly, input\_zbins can be passed.
The user can choose to use bins of true redshift by setting the input parameter bin\_in\_truez equal to True (default is False, to bin in photo-_z_).
Statistical measures are based on the photo-$z$ error: $\Delta z_{1+z_p} = (z_t-z_p)/(1+z_p)$ where $z_t$ is the true redshift, and $z_p$ the photo-$z$, of the test-set galaxy.
For some statistics, catastrophic outlier rejection (COR) is done first, and test galaxies in the bin with $|z_t-z_p| >$ stats\_COR (default 1.5) are rejected.
Outliers are defined as in the Science Requirements Document: $|\Delta z_{1+z_p}| > 3\sigma_{\rm IQR}$ _and_ $|\Delta z_{1+z_p}| > 0.06$. 

**Outputs:** Writes statistics to file output/run\__runid_/analysis/stats.dat. Columns of this file are described below. Will instead write to output/run\__runid_/analysis/stats_truezbins.dat if the user input parameter bin\_in\_truez is set to True (default is False, default to bin in photo-z).

#### Table 3: Statistical Measures 
| Col | Column Name | Description |
| :-- | :-- | :-- |
|  0 | zlow | photo-z bin lower limit |
|  1 | zhi  | photo-z bin upper limit |
|  2 | meanz    | the mean zphot of galaxies in bin |
|  3 | CORmeanz | post-COR mean zphot of galaxies in bin |
|  4 | fout    | fraction of outliers |
|  5 | CORfout | post-COR fraction of outliers |
|  6 | stdd    | standard deviation in $\Delta z_{1+z_p}$ of all galaxies in bin |
|  7 | bias    | mean $\Delta z_{1+z_p}$ of all galaxies in bin |
|  8 | outbias | mean $\Delta z_{1+z_p}$ of all outlier galaxies in bin |
|  9 | IQR     | interquartile range of $\Delta z_{1+z_p}$ |
| 10 | IQRstdd | stdandard deviation from the IQR ( = IQR / 1.349 ) |
| 11 | IQRbias | bias of test galaxies in the IQR  |
| 12 | CORstdd     | post-COR stdd |
| 13 | CORbias     | post-COR bias |
| 14 | CORoutbias  | post-COR outlier bias |
| 15 | CORIQR      | post-COR IQR |
| 16 | CORIQRstdd  | post-COR IQR stdd |
| 17 | CORIQRbias  | post-COR IQR bias |
| 18 | estdd       | error in stdd |
| 19 | ebias       | error in bias |
| 20 | eoutbias    | error in outlier bias |
| 21 | eIQR        | error in IQR |
| 22 | eIQRstdd    | error in IQR stdd |
| 23 | eIQRbias    | error in IQR bias |
| 24 | eCORstdd    | error in post-COR stdd |
| 25 | eCORbias    | error in post-COR bias |
| 26 | eCORoutbias | error in post-COR outlier bias |
| 27 | eCORIQR     | error in post-COR IQR |
| 28 | eCORIQRstdd | error in post-COR IQR stdd |
| 29 | eCORIQRbias | error in post-COR IQR bias |

### Section 5.4.2. cmnn_analysis.make_stats_plots
Called by `cmnn_run.run`.

**What it does:** Plots the photo-z statistics as a function of photo-z bin for a _runid_ (from stats.dat).
By default, three plots for three statistics are made: robust standard deviation, robust bias, and fraction of outliers.
The default is to apply catastrophic outlier rejection (COR) to the robust standard deviation and robust bias statistics (COR is defined by user input parameter stats\_COR for cmnn\_run.run).

**Outputs:** Saves plots to the output/run\__runid_/analysis/ directory (CORIQRstdd.png, CORIQRbias.png, fout.png).

**Options:** When run stand-alone (i.e., not from cmnn\_run.run), the user may specify which of the statistical measures of photo-z quality a plot should be created for, and/or whether multiple _runids_ be co-plotted. When multiple _runids_ are co-plotted, the plots are saved to the directory "output/stats_plots/" with names formatted like "fout\_runid1\_runid2\_runid3.png". The Examples above demonstrate how to plot the statistical results from multiple runs into a single figure using the options in the table below.

#### Table 4: Additional Arguments for Making Multi-Run Plots of Statistical Measures
| Inputs | Type | Default | Description |
| :-- | :-- | :-- | :-- |
| user\_stats | str[M] | ['fout','CORIQRstdd','CORIQRbias'] | list of statistics for which to make plots; currently allowed to be any number of ['fout', 'stdd', 'bias', 'outbias', 'IQR', 'IQRstdd', 'IQRbias', 'CORstdd', 'CORbias', 'CORoutbias', 'CORIQR', 'CORIQRstdd', 'CORIQRbias'] |
| show\_SRD | bool | True | if True, the SRD target values are shown as dashed horizontal lines (ls.st/lpm-17) |
| show\_binw | bool | True | if True, thin horizontal bars are plotted to show the redshift bins |
| multi\_run\_ids | str[N] | [runid] | array of multiple run ids to co-plot |
| multi\_run\_labels | str[N] | ['run '+runid] | array of legend labels that describe each run |
| multi\_run\_colors | str[N] | ['blue','orange','red','green','darkviolet'] | array of color names to use for each run (OK to pass $>5$ if $N>5$) |

### Section 5.4.3. `cmnn_analysis.make_tzpz_plot`
Called by `cmnn_run.run`.

**What it does:** Plots the true (y-axis) vs. the photometric redshifts (x-axis) as a 2d histogram.
Includes user-specified options to represent outliers with colored points, to draw polygons, and/or to plot phot/true redshifts on the y/x axes instead.

**Outputs:** Saves plot to output/run\__runid_/analysis/tzpz.png (or pztz.png if the user decides to swap the axes).

### Section 5.4.4. `cmnn_analysis.make_hist_plots`
Called by `cmnn_run.run`.

**What it does:** Plots histograms of the results: photometric redshifts (compared with true redshifts), size of the CMNN subset of training galaxies, and size of the training set used (after any color or magnitude cuts).

**Outputs:** Saves plot to the output/run\__runid_/analysis/ directory (hist\_ncm.png, hist\_ntr.png, hist\_z.png).

### Section 5.4.5. `cmnn_analysis.get_stats`
Called by `cmnn_analysis.make_stats_file`.

**What it does:** When passed a full set of true and photometric redshifts and a desired redshift bin size, calculates all statistical measures (Table 3) for that redshift bin.

**Returns:** A set of values for all of the statistical measures in Table 3 (i.e., from column 2 `meanz` and up).

### Section 5.5.1. `cmnn_tools.convert_visits_to_depths`

**What it does:** Converts the number of standard 30 second visits to be done in each filter _ugrizy_ into a 5$\sigma$ limiting magnitude depth for each filter.<br>

**Returns:** The 5$\sigma$ limiting magnitude depths in _ugrizy_ as a 6-element array.

**Example:**
```
>>> import cmnn_tools
>>> results_A = cmnn_tools.convert_visits_to_depths( [28, 40, 92, 92, 80, 80] )
>>> print(results_A)
[ 25.70894754  27.00257499  27.15473478  26.45473478  25.67886248 24.47886248]
```

### Section 5.5.2. cmnn_tools.convert_year_to_depths_baseline

**What it does:** Convert the year of a survey into the $5{\sigma}$ limiting magnitudes depths in _ugrizy_, assuming a baseline LSST observing strategy.<br>

**Returns:** the $5{\sigma}$ limiting magnitudes depths in _ugrizy_ as a 6-element array.

**Example:**
```
>>> import cmnn_tools
>>> results_B = cmnn_tools.convert_year_to_depths_baseline( 5 )
>>> print(results_B)
[ 25.70894754  27.00257499  27.15473478  26.45473478  25.67886248  24.47886248]
```